version: '3.9'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: default1
      POSTGRES_DB: softexpert
  adminer:
    image: adminer
    ports:
      - 9000:8080
