version: '3.9'
services:
  php:
    build:
      context: ./docker/SymfonyApp
    volumes:
      - ./:/var/www/symfony_docker
    depends_on:
      - db
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www/symfony_docker
      - ./docker/Nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - php
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./database/initial_dump.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    ports:
      - 9000:8080
    depends_on:
      - db
